name: yaml_flow

on:
  workflow_dispatch:

jobs:
  demo_run:
    runs-on: ubuntu-latest

    env:
      greet: "hello developers"

    steps:
      - name: run message
        run: echo "$greet your internship"
