name: github-workflow

on:
  workflow_dispatch:

jobs:
  demo_run:
    runs-on: self-hosted

    env:
      greet: "welcome developer"
 
    steps:
      - name: run_demo
        run: echo "this is my runner $greet"
