
name: myactions

on:
  workflow_dispatch:

jobs:
  demo_job:
    runs-on: self-hosted

    env:
      greeting: hello

    steps:
      - name: Run demo
        run: echo "this is ec2 demo, so $greeting"
